name: Release
run: echo "The actor is ${{github.actor}}"
on: push
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GH_TOKEN}}
    - run:  | 
        IMG="ghcr.io/${{github.repository}}"
        IMG=${IMG@L}
        docker build --tag $IMG:latest .
        docker push --all-tags $IMG
